# This defines a pipeline to pack into Nuget.

trigger: none

stages:
  - stage: build
    displayName: Build
    jobs:
    - template: jobs.yml
      parameters:
        debug: false
        name: Windows
    - template: jobs.yml
      parameters:
        debug: false
        name: Linux
    - template: jobs.yml
      parameters:
        debug: false
        name: macOS
    - template: jobs.yml
      parameters:
        debug: false
        name: Nuget